version: '3'

services:

  mojp-dbs-search-api:
    build: .
    image: mojp-dbs-search-api
    ports:
      - "8000:8000"
    environment:
    - DPP_ELASTICSEARCH=elasticsearch:9200
    volumes:
    - ../mojp-dbs-pipelines/data:/opt/mojp-dbs-pipelines/data
